# SD-WAN controller telemetry (written by laptop daemon → /var/lib/deca/sdwan_metrics.influx)
[[inputs.exec]]
  commands = ["/usr/local/bin/deca-sdwan-metrics.sh"]
  timeout = "3s"
  interval = "5s"
  data_format = "influx"
