# DECA swanctl IPsec — PE2 template (station2). See pe1.conf for copy_dscp notes.

connections {
    deca-sdwan {
        version = 2
        local_addrs = 192.168.50.20
        remote_addrs = 192.168.50.10
        proposals = aes128-sha256-x25519
        local {
            auth = pubkey
            certs = station2-cert.pem
            id = "CN=station2"
        }
        remote {
            auth = pubkey
            id = "CN=station1"
        }
        children {
            net {
                local_ts = 10.100.2.1/32,10.10.2.0/30,10.100.4.1/32,10.10.4.0/30,10.101.2.0/29,10.101.4.0/29
                remote_ts = 10.100.1.1/32,10.10.1.0/30,10.100.3.1/32,10.10.3.0/30,10.101.1.0/29,10.101.3.0/29
                esp_proposals = aes128-sha256
                copy_dscp = out
                start_action = start
                dpd_action = restart
            }
        }
        dpd_delay = 30s
    }
}
